[package]
name              = "midnight-did-serde"
version.workspace = true
edition.workspace = true

[dependencies]
midnight-did = { workspace = true }

derive_more      = { workspace = true }
identus-did-core = { workspace = true }
serde            = { workspace = true, optional = true, features = [ "derive" ] }
serde_json       = { workspace = true }

[features]
default   = [  ]
serde-cli = [ "dep:serde" ]
