[package]
name              = "midnight-did-serde"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
midnight-did = { workspace = true }

derive_more                 = { workspace = true }
identus-did-core            = { workspace = true }
midnight-base-crypto_v6     = { workspace = true }
midnight-coin-structure_v6  = { workspace = true }
midnight-onchain-runtime_v6 = { workspace = true }
midnight-serialize_v6       = { workspace = true }
midnight-storage_v6         = { workspace = true }
serde                       = { workspace = true, optional = true, features = [ "derive" ] }
serde_json                  = { workspace = true }

[features]
default = [  ]
js-cli  = [ "dep:serde" ]
