[workspace]
resolver = "3"
members = [
  "midnight-did",
  "midnight-did-indexer-client",
  "midnight-did-resolver",
  "midnight-did-serde",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
midnight-did-indexer-client = { path = "midnight-did-indexer-client" }
midnight-did                = { path = "midnight-did" }
midnight-did-serde          = { path = "midnight-did-serde" }

midnight-base-crypto_v6     = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-base-crypto", tag = "ledger-6.1.0-alpha.2" }
midnight-coin-structure_v6  = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-coin-structure", tag = "ledger-6.1.0-alpha.2" }
midnight-onchain-runtime_v6 = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-onchain-runtime", tag = "ledger-6.1.0-alpha.2" }
midnight-serialize_v6       = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-serialize", tag = "ledger-6.1.0-alpha.2" }
midnight-storage_v6         = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-storage", tag = "ledger-6.1.0-alpha.2" }

identus-apollo            = { git = "https://github.com/hyperledger-identus/neoprism", rev = "3d1a18d57804a9d9541183c62eb5f3cf83da7f40" }
identus-did-core          = { git = "https://github.com/hyperledger-identus/neoprism", rev = "3d1a18d57804a9d9541183c62eb5f3cf83da7f40" }
identus-did-resolver-http = { git = "https://github.com/hyperledger-identus/neoprism", rev = "3d1a18d57804a9d9541183c62eb5f3cf83da7f40" }

anyhow             = { version = "1" }
async-trait        = { version = "0.1" }
axum               = { version = "0.8" }
chrono             = { version = "0.4" }
clap               = { version = "4" }
derive_more        = { version = "2" }
graphql_client     = { version = "0.14" }
lazybe             = { version = "0.2" }
reqwest            = { version = "0.12", default-features = false }
serde              = { version = "1" }
serde_json         = { version = "1" }
strum              = { version = "0.27" }
tokio              = { version = "1" }
tower              = { version = "0.5" }
tower-http         = { version = "0.6" }
tracing            = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
utoipa             = { version = "5" }
utoipa-swagger-ui  = { version = "9" }
