services:
  did-resolver:
    build:
      context: ..
      dockerfile: did-resolver-service/Dockerfile
    environment:
      RESOLVER_HOST: 0.0.0.0
      RESOLVER_PORT: 3001
      MIDNIGHT_INDEXER_HTTP_URL: http://127.0.0.1:8088/api/v3/graphql
      MIDNIGHT_INDEXER_WS_URL: ws://127.0.0.1:8088/api/v3/graphql/ws
    ports:
      - "0:3001"
