//! Derive macros for `midnight-storage`.
extern crate proc_macro;
use proc_macro2::{TokenStream, TokenTree};
use quote::{ToTokens, quote};
use syn::{
    Attribute, Data, DeriveInput, Field, Fields, Index, Meta, parse_macro_input, parse_quote,
};

/// #[derive(Storable)] macro.
///
/// Any children of type Sp<_> annotated with #[storable(child)] will be treated as child-nodes
/// in the Storable implementation, as such the
/// generated `Storable` impl will return the `ArenaKey` of any such annotated fields
/// as part of `Storable::children(..)`, and they will consiquently be ommited from
/// the binary representation as generated by `Storable::to_binary_repr`, and in
/// `Storable::from_binary_repr` they will be populated via `loader.get_next(..)`.
///
/// Any children not annotated with #[storable(child)] will be in-lined, i.e. any of their
/// children will be included in parent.children(), and their binary representation will be
/// included in parent.to_binary_repr.
///
/// Optionally, if parameterised over D: DB, (i.e. children of type Sp<_, D>) the
/// struct can be annotated with #[storable(db = D)]. This results in the `Storable`
/// impl being implemented for `Storable<D>`. If ommited `Storable` is implemented for
/// `Storable<DefaultDB>`.
///
/// Enums and structs with unnamed fields are not supported.
#[proc_macro_derive(Storable, attributes(storable))]
pub fn derive_storable(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let name = input.ident.clone();

    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let db = generic_db(&input).unwrap_or(quote! {DefaultDB});

    let children_impl = derive_children(&input.data, &db);
    let to_binary_repr_impl = derive_to_binary_repr(&input.data, &db);
    let from_binary_repr_impl = derive_from_binary_repr(&input.data);

    let expanded = quote! {
        impl #impl_generics Storable<#db> for #name #ty_generics #where_clause {
            fn children(&self) -> Vec<ArenaKey<<#db as DB>::Hasher>> {
                #children_impl
            }

            fn to_binary_repr<W: std::io::Write>(&self, writer: &mut W) -> Result<(), std::io::Error> {
                #to_binary_repr_impl
            }

            fn from_binary_repr<R: std::io::Read>(reader: &mut R, child_hashes: &mut impl Iterator<Item = ArenaKey<<#db as DB>::Hasher>>, loader: &impl Loader<#db>) -> Result<Self, std::io::Error> {
                #from_binary_repr_impl
            }
        }
    };

    proc_macro::TokenStream::from(expanded)
}

fn generic_db(input: &DeriveInput) -> Option<TokenStream> {
    let attrs: Vec<&Attribute> = input
        .attrs
        .iter()
        .filter(|attr| (**attr).path().is_ident("storable"))
        .collect();

    for attr in attrs {
        if let Meta::List(ref list) = attr.meta {
            let tokens: Vec<TokenTree> = list.tokens.clone().into_iter().collect();
            if tokens[0].to_string() == "db" && tokens[1].to_string() == "=" {
                return Some(tokens[2].clone().into_token_stream());
            }
        }
    }

    None
}

#[derive(PartialEq)]
enum FieldTypes {
    Child,
    Inline,
}

fn child_field(field: &Field) -> FieldTypes {
    let expt_child = parse_quote! { #[storable(child)] };

    for attr in field.attrs.iter() {
        if attr == &expt_child {
            return FieldTypes::Child;
        }
    }

    FieldTypes::Inline
}

fn derive_children(data: &Data, db: &TokenStream) -> TokenStream {
    match *data {
        Data::Struct(ref data) => {
            let children_hashes = match data.fields {
                Fields::Named(ref f) => f.clone().named.into_iter().map(|field| {
                    let ident = field.ident.clone().expect("named field");
                    match child_field(&field) {
                        FieldTypes::Child => quote! {child_hashes.push(Sp::hash(&self.#ident).into())},
                        FieldTypes::Inline => quote! {child_hashes.append(&mut Storable::<#db>::children(&self.#ident))},
                    }
                }).collect::<Vec<TokenStream>>(),
                Fields::Unnamed(ref f) => {
                    f.clone().unnamed.into_iter().enumerate().map(|(i,field)| {
                        let index = Index::from(i);
                        match child_field(&field) {
                            FieldTypes::Child => {
                                quote! {child_hashes.push(Sp::hash(&self.#index).into())}
                            },
                            FieldTypes::Inline => {
                                quote! {child_hashes.append(&mut Storable::<#db>::children(&self.#index))}
                            },
                        }
                    }).collect::<Vec<TokenStream>>()
                }
                _ => panic!("Unable to derive Storable with Unit fields."),
            }.into_iter();
            quote! {
                let mut child_hashes = Vec::new();
                #(#children_hashes;)*
                child_hashes
            }
        }
        _ => {
            panic!("Only able to derive Storable for Structs")
        }
    }
}

fn derive_to_binary_repr(data: &Data, db: &TokenStream) -> TokenStream {
    match *data {
        Data::Struct(ref data) => {
            let child_binary_repr = match data.fields {
                Fields::Named(ref f) => f
                    .clone()
                    .named
                    .into_iter()
                    .map(|field| {
                        let ident = field.ident.clone().expect("named field");
                        match child_field(&field) {
                            FieldTypes::Child => quote! {},
                            FieldTypes::Inline => {
                                quote! {Storable::<#db>::to_binary_repr(&self.#ident, writer)?}
                            }
                        }
                    })
                    .collect::<Vec<TokenStream>>()
                    .into_iter(),
                Fields::Unnamed(ref f) => f
                    .clone()
                    .unnamed
                    .into_iter()
                    .enumerate()
                    .map(|(i, field)| {
                        let index = Index::from(i);
                        match child_field(&field) {
                            FieldTypes::Child => quote! {},
                            FieldTypes::Inline => {
                                quote! {Storable::<#db>::to_binary_repr(&self.#index, writer)?}
                            }
                        }
                    })
                    .collect::<Vec<TokenStream>>()
                    .into_iter(),
                _ => panic!("Unable to derive Storable on Unit fields"),
            };
            quote! {
                #(#child_binary_repr;)*
                Ok(())
            }
        }
        _ => {
            panic!("Only able to derive Storable for Structs")
        }
    }
}

fn derive_from_binary_repr(data: &Data) -> TokenStream {
    match *data {
        Data::Struct(ref data) => {
            match data.fields {
                Fields::Named(ref f) => {
                    let deserialize_children = f.clone().named.into_iter().map(|field| {
                        let ident = field.ident.clone().expect("named field");
                        match child_field(&field) {
                            FieldTypes::Child => quote! {#ident: loader.get_next(child_hashes)?},
                            FieldTypes::Inline => quote! {#ident: Storable::from_binary_repr(reader, child_hashes, loader)?},
                        }
                    });
                    quote! {
                        Ok(Self {
                            #(#deserialize_children,)*
                        })
                    }
                }
                Fields::Unnamed(ref f) => {
                    let deserialize_children = f.clone().unnamed.into_iter().map(|field| {
                        match child_field(&field) {
                            FieldTypes::Child => quote! {loader.get_next(child_hashes)?},
                            FieldTypes::Inline => {
                                quote! {Storable::from_binary_repr(reader, child_hashes, loader)?}
                            }
                        }
                    });
                    quote! {
                        Ok(Self (
                            #(#deserialize_children,)*
                        ))
                    }
                }
                _ => panic!("Only able to derive Storable with named fields"),
            }
        }
        _ => {
            panic!("Only able to derive Storable for Structs")
        }
    }
}
