use crate::serialize::{self, Deserializable, Serializable, Versioned};
#[cfg(all(feature = "proptest", test))]
use crate::serialize::{NetworkId, deserialize, serialize, serialized_size};
#[cfg(feature = "proptest")]
use crate::storage::serialize::randomised_serialization_test;
#[cfg(feature = "proptest")]
use proptest_derive::Arbitrary;
#[cfg(feature = "serde")]
use serde::Serialize;

#[derive(Clone, PartialEq, Eq, Debug, Serializable, Deserializable)]
#[cfg_attr(feature = "serde", derive(Serialize))]
#[cfg_attr(feature = "proptest", derive(Arbitrary))]
pub struct CostModel {
    pub noop_constant: u64,
    pub noop_linear: u64,
    pub lt: u64,
    pub eq: u64,
    pub type_: u64,
    pub size: u64,
    pub new: u64,
    pub and: u64,
    pub or: u64,
    pub neg: u64,
    pub log: u64,
    pub root: u64,
    pub pop: u64,
    pub popeq_constant: u64,
    pub popeq_linear: u64,
    pub popeqc_constant: u64,
    pub popeqc_linear: u64,
    pub addi: u64,
    pub subi: u64,
    pub push_constant: u64,
    pub push_linear: u64,
    pub pushs_constant: u64,
    pub pushs_linear: u64,
    pub branch: u64,
    pub jmp: u64,
    pub add: u64,
    pub sub: u64,
    pub concat_constant: u64,
    pub concat_linear: u64,
    pub concatc_constant: u64,
    pub concatc_linear: u64,
    pub member_constant: u64,
    pub member_linear: u64,
    pub member_logarithmic: u64,
    pub rem_constant: u64,
    pub rem_linear: u64,
    pub rem_logarithmic: u64,
    pub remc_constant: u64,
    pub remc_linear: u64,
    pub remc_logarithmic: u64,
    pub dup: u64,
    pub swap: u64,
    pub idx_constant: u64,
    pub idx_linear: u64,
    pub idx_logarithmic: u64,
    pub idxc_constant: u64,
    pub idxc_linear: u64,
    pub idxc_logarithmic: u64,
    pub idxp_constant: u64,
    pub idxp_linear: u64,
    pub idxp_logarithmic: u64,
    pub idxpc_constant: u64,
    pub idxpc_linear: u64,
    pub idxpc_logarithmic: u64,
    pub ins_constant: u64,
    pub ins_linear: u64,
    pub ins_logarithmic: u64,
    pub insc_constant: u64,
    pub insc_linear: u64,
    pub insc_logarithmic: u64,
    pub ckpt: u64,
}

impl Versioned for CostModel {
    const VERSION: Option<serialize::Version> = Some(serialize::Version { major: 1, minor: 0 });
    const NETWORK_SPECIFIC: bool = false;
}

#[cfg(feature = "proptest")]
randomised_serialization_test!(CostModel);

pub const DUMMY_COST_MODEL: CostModel = CostModel {
    noop_constant: 0,
    noop_linear: 0,
    lt: 1,
    eq: 1,
    type_: 1,
    size: 1,
    new: 1,
    and: 1,
    or: 1,
    neg: 1,
    log: 1,
    root: 1,
    pop: 1,
    popeq_constant: 1,
    popeq_linear: 1,
    popeqc_constant: 1,
    popeqc_linear: 1,
    addi: 1,
    subi: 1,
    push_constant: 1,
    push_linear: 1,
    pushs_constant: 1,
    pushs_linear: 100,
    branch: 1,
    jmp: 1,
    add: 1,
    sub: 1,
    concat_constant: 1,
    concat_linear: 10,
    concatc_constant: 1,
    concatc_linear: 1,
    member_constant: 1,
    member_linear: 1,
    member_logarithmic: 1000,
    rem_constant: 1,
    rem_linear: 1,
    rem_logarithmic: 1000,
    remc_constant: 1,
    remc_linear: 1,
    remc_logarithmic: 10,
    dup: 1,
    swap: 1,
    idx_constant: 1,
    idx_linear: 1,
    idx_logarithmic: 1000,
    idxc_constant: 1,
    idxc_linear: 1,
    idxc_logarithmic: 10,
    idxp_constant: 1,
    idxp_linear: 1,
    idxp_logarithmic: 1000,
    idxpc_constant: 1,
    idxpc_linear: 1,
    idxpc_logarithmic: 10,
    ins_constant: 1,
    ins_linear: 1,
    ins_logarithmic: 1000,
    insc_constant: 1,
    insc_linear: 1,
    insc_logarithmic: 10,
    ckpt: 1,
};
