// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Did = string;

export type DidDocument = { "@context": Array<string>, id: Did, verificationMethod: Array<VerificationMethod>, authentication: Array<VerificationMethodOrRef> | null, assertionMethod: Array<VerificationMethodOrRef> | null, keyAgreement: Array<VerificationMethodOrRef> | null, capabilityInvocation: Array<VerificationMethodOrRef> | null, capabilityDelegation: Array<VerificationMethodOrRef> | null, service: Array<Service> | null, };

export type Service = { id: string, type: ServiceType, serviceEndpoint: ServiceEndpoint, };

export type ServiceEndpoint = StringOrMap | Array<StringOrMap>;

export type ServiceType = string | Array<string>;

export type StringOrMap = string | Record<string, any>;

export type VerificationMethod = { id: string, type: string, controller: string, publicKeyJwk: Record<string, any> | null, };

export type VerificationMethodOrRef = VerificationMethod | string;
